export enum BindableInputType {
  Checkbox = "checkbox",
  Color = "color",
  Date = "date",
  DatetimeLocal = "datetime-local",
  Email = "email",
  File = "file",
  Hidden = "hidden",
  Month = "month",
  Number = "number",
  Password = "password",
  Radio = "radio",
  Range = "range",
  Search = "search",
  Tel = "tel",
  Text = "text",
  Time = "time",
  Url = "url",
  Week = "week"
}
